version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR..!!!
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 723330070958.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      - echo Building the Docker image..!!!
      - docker build -t aws-ecs-flask-app-repo .
      - docker tag aws-ecs-flask-app-repo:latest 723330070958.dkr.ecr.ap-south-1.amazonaws.com/aws-ecs-flask-app-repo:latest

  post_build:
    commands:
    - echo Pushing the Docker image into ECR..!!!
    - docker push 723330070958.dkr.ecr.ap-south-1.amazonaws.com/aws-ecs-flask-app-repo:latest
    - echo Creating image definitions file..!!!
    - printf '[{"name":"%s","imageUri":"&s"}]' "$IMAGE_REPO_NAME" "$REPOSITORY_URI=$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json